---
- name: install mysql client on all hosts
  hosts: all
  user: ec2-user
  become: yes
  vars_files:
  - group_vars/all.yml

  roles:
    - common

- name: deploy MySQL and configure the databases
  hosts: database
  user: ec2-user
  become: yes
  roles:
    - mysql

- name: configure and deploy the webservers and application code
  hosts: web
  user: ec2-user
  become: yes
  roles:
    - web
    #- { role: newrelic, newrelic_license_key: ab0e123c0bdc8c77cc5922bd67416a080518181 }
    - n98-magerun
    - composer
    - redis
    - memcache
    - magento
