- name: Install memcached
  apt: name={{ item }} state=present
  with_items:
    - memcached
  when: ansible_os_family == "Debian"

- name: Install memcached
  yum: name={{ item }} state=present
  with_items:
    - memcached
  when: ansible_os_family == "RedHat"